### ISSUE TITLE
sharing state between pages

### ISSUE THREAD

**Issue by sendlo** [dogada/fast-redux#2]
I found this through NextJS and was playing around with this a bit.  I got lost when trying to share state data between pages.  Is this possible and can you add an example?  

For example, in your NextJS example, how can you access the "build" state object in the about page.

**Comment by dogada** [comment]
All pages use same Redux store. The example is already in the repo, see: https://github.com/dogada/fast-redux/blob/master/examples/nextjs-preact-code-splitting/config/redux.js

**Comment by joshuaquek** [comment]
@sendlo I think you are wondering how to use a variable in the "about" namespace store inside the homepage right? I have built an example prototype based on @dogada 's code example. 

It allows you to get the "build" and "version" variable from the two different namespaceconfig states (different state trees)

...and access these variables from a combined state in a single page.

**Comment by joshuaquek** [comment]
Example here:

https://github.com/joshuaquek/redux-multiple-states-nextjs

**Comment by sendlo** [comment]
Thanks.  Yes, that was what I was curious about.
I'm still not thrilled with this solution though.  Say I have 2 pages that both need to know about the active user.  Page A looks up the user and sets the data in its redux namespace.  But what happens if the user went to page B first?  Now the data is in the page B namespace instead of A.  Also, what happens when the user data is updated on page A and page B?  Where is the data updated?  Do we end up with user data in 2 different namespaces?

Nice job with this.  I think it works if each page needs unique data.  I just don't think its going to work for me.

**Comment by dogada** [comment]
@sendlo Page A and page B can use same shared namespace, for example named 'userdata'. A page can use several namespaces. Each namespace is stored in global store, so data is preserved between page loads. The main purpose of the namespaces is to split whole store on chunks and load only those namespaces that are used on the current page.

**Comment by sendlo** [comment]
Ah. I didn't realize a page could use multiple namespaces.  So I can call namespaceConfig multiple times on the same page, with different namespaces, and have access to different "action" and "getState" methods.
Thanks very much. I'll take a closer look.

**Comment by dogada** [comment]
Yup, namespace is just part of shared state.

**Comment by joshuaquek** [comment]
@sendlo  Yes correct, you can take a look at line 28 of the file below to see how one can use two namespaces in a single page:

https://github.com/joshuaquek/redux-multiple-states-nextjs/blob/master/containers/about.js
