### ISSUE TITLE
Example for staticPropertyConfig

### ISSUE THREAD

**Issue by colinrobertbrooks** [dogada/fast-redux#3]
The [comments](https://github.com/dogada/fast-redux/blob/master/src/object.js#L5) for `staticPropertyConfig` in `src/object.js` reference ` examples/async/src/actions/postsByReddit.js`, which doesn't exist. The [example](https://github.com/dogada/fast-redux/blob/master/examples/async/src/stores/postsByReddit.js#L1) in `examples/async/src/stores/postsByReddit.js` actually uses `dynamicPropertyConfig`.

**Comment by dogada** [comment]
@colinrcummings thanks for your feedback, I fixed the link in the comments (early I used to split store on actions and reducers but last time prefer to keep them in single store).

About staticPropertyConfig. It's optional helper util very similar to dynamicPropertyConfig. They both update a property of an object, but dynamicPropertyConfig requires you to provide property name in runtime as argument to action. But for staticPropertyConfig property name isn't passed to action and always same. It have sense only for objects with known and limited shape, say you have state with shape like `{settings, language, user}`, and so you can define an action that will update settings property of the state with something like 
```
const {
  propertyAction: settingsAction,
  getPropertyState: getSettingsState
} = staticPropertyConfig(action, 'settings')

export const updateSettings = settingsAction('updateSettings',
  (state, diff) => ({
    ...state,
    ...diff
  })
)
```
In real word you will need dynamicPropertyConfig much more often than staticPropertyConfig. I even plan to move dynamicPropertyConfig into `namespaceConfig`, so above-mentioned postsByReddit.js can be rewritten with less code:
```js
const DEFAULT_STATE = {}
const DEFAULT_REDDIT_STATE = {
  isFetching: false,
  didInvalidate: false,
  items: []
}
const {action, propertyAction} = namespaceConfig('postsByReddit', DEFAULT_STATE, DEFAULT_REDDIT_STATE)
```
In this case you will not need to call `dynamicPropertyConfig` at all. What do you think?

By the way you can find more fast-redux example in my WIP React starter kit:
https://github.com/dogada/microchain/tree/master/webapp/store

Do you use fast-redux in some project? How can you compare it with Redux: easy, harder, faster, slowly, etc?

**Comment by colinrobertbrooks** [comment]
@dogada, thanks for your detailed response. I have been experimenting with `fast-redux` in a `next`-based rewrite of a client-rendered app so I can also code split reducer logic isomorphicly. I'm still working through how to organize it in conjunction with `next-redux-wrapper`, but I think you have a powerful abstraction here--"fast" in terms of both performance, which you highlight thoroughly in the current README, but also in terms of writing less boilerplate. This second type of speed, however, may be a cognitive barrier to entry for some potential users: having to be very comfortable with `redux`'s existing abstractions, which are powerful in their own right, before finding `fast-redux` approachable. The current examples, while thorough, may not be self-explanatory to all potential users--especially those still wrapping their heads around `redux` itself. Therefore, I think the README could benefit from a section comparing a feature written using `redux` with the same feature written using`fast-redux` (e.g. without `fast-redux` you'd write it this, but with `fast-redux` you write this). This is just my opinion. What do you think? l'd be happy to work on this with you.

**Comment by dogada** [comment]
@colinrcummings, yeah you're right it's harder to explain things, then do them. I added some links to README where people can compare same application, implemented with Redux and FastRedux.

Please drop me a link to your app as well if you will decide to opensource it sometime.
