### ISSUE TITLE
Example for use with redux-persist

### ISSUE THREAD

**Issue by pcardune** [dogada/fast-redux#4]
Great library!

I'd like to see an example for how `redux-fast` can be used alongside [redux-persist](https://github.com/rt2zz/redux-persist), in particular with nested persists, and with transforms.

It seems relatively straightforward to persist the entire tree by wrapping the `redux-fast` rootReducer, but then you have to combine all the transforms for the entire state tree at the root level as well, which somewhat defeats the code-splitting functionality.

If `namespaceConfig()` gave an option to wrap the reducer it produces, I think that would solve the problem. Perhaps something like:

```js
const { action: gameAction, getState: getGameState } = namespaceConfig(
  'GameState',
  {score: 0},
  (reducer) => persistReducer(
    {key: 'GameState', storage, transforms: [myTransform]},
    reducer
  )
);
```

Is this already possible some other way or should I attempt to submit a pull request with this additional functionality?

**Comment by dogada** [comment]
Hi Paul, thanks for your interest. I use fast-redux reducers as drop-in replacement for the classic Redux reducers. The goal is to use fast-redux seamlessly with all Redux tools. So before extending fast-redux with support for redux-persist or another library, can you give an example of the code that works with Redux but doesn't yet work with fast-redux? State of fast-redux is the same object with keys, so I suppose you should be able to save and restore only some keys like you can do with classic redux and redux-persist.
